apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- piraeus.yaml
- linstor-cluster.yaml
- linstor-nvme-cluster.yaml
- storageclass.yaml
- snapshot-controller.yaml
- snapshotclass.yaml