apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: mikrotik-peering
spec:
  bgpInstances:
  - name: "bgp-instance-1"
    localASN: 64512
    peers:
    - name: "mikrotik"
      peerAddress: "10.122.0.1"
      peerASN: 64512
      peerConfigRef:
        name: cilium-peer
