apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway-api.yaml
- tlsroute.yaml
- cilium.yaml
- loadbalancer.yaml
- bgp-advertisement.yaml
- bgp-cluster-config.yaml
- bgp-peer-config.yaml
- gateway.yaml